# Generated by Django 2.1.4 on 2019-01-31 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_text', models.TextField(max_length=200, verbose_name='発言')),
                ('talk_datetime', models.DateTimeField(verbose_name='発言日時')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_text', models.TextField(default='', max_length=200, verbose_name='発言')),
                ('talk_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発言日時')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), '名前には半角英数字、アンダーバー、ハイフンのみ指定できます。', 'invalid')], verbose_name='ユーザーID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名前')),
                ('isInsite', models.IntegerField(choices=[(1, '入室中'), (2, '退室')], default=2, verbose_name='入室状態')),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
        migrations.AddField(
            model_name='chat_log',
            name='talk_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Talk'),
        ),
        migrations.AddField(
            model_name='chat_log',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
    ]
