# Generated by Django 2.1.4 on 2019-01-23 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190120_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_datetime',
            field=models.DateField(default=datetime.datetime.now, verbose_name='発言日時'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
    ]
