# Generated by Django 2.1.4 on 2018-12-24 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ログＩＤ')),
                ('talk_text', models.CharField(max_length=200, verbose_name='発言')),
                ('talk_datetime', models.DateField(verbose_name='発言日時')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='発言ＩＤ')),
                ('talk_text', models.CharField(default='', max_length=200, verbose_name='発言')),
                ('talk_datetime', models.DateField(verbose_name='発言日時')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ユーザーＩＤ')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名前')),
                ('isInsite', models.IntegerField(choices=[(1, '入室中'), (2, '退室')], default=2, verbose_name='入室状態')),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
        migrations.AddField(
            model_name='chat_log',
            name='talk_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Talk'),
        ),
        migrations.AddField(
            model_name='chat_log',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Users'),
        ),
    ]
