# Generated by Django 2.1.4 on 2019-01-15 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ユーザーＩＤ'),
        ),
    ]
