# Generated by Django 2.1.4 on 2019-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190115_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='talk_text',
            field=models.TextField(max_length=200, verbose_name='発言'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_text',
            field=models.TextField(default='', max_length=200, verbose_name='発言'),
        ),
    ]
