# Generated by Django 2.1.4 on 2019-01-24 13:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190124_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_log',
            name='talk_datetime',
            field=models.DateTimeField(verbose_name='発言日時'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='発言日時'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), '名前には半角英数字、アンダーバー、ハイフンのみ指定できます。', 'invalid')], verbose_name='ユーザーID'),
        ),
    ]
